### ISSUE TITLE
Compile Error?

### ISSUE THREAD

**Issue by jiangzhengkai** [waymo-research/waymo-open-dataset#123]
Hi, I am using **waymo-open-dataset/pip_pkg_scripts/build.sh**, however, there exists such errors.

`
INFO: Build completed, 6 tests FAILED, 21 total actions
//third_party/camera:camera_model_test                                   PASSED in 0.2s
//waymo_open_dataset/math:aabox2d_test                                   PASSED in 0.2s
//waymo_open_dataset/math:box2d_test                                     PASSED in 0.2s
//waymo_open_dataset/math:exactfloat_test                                PASSED in 63.4s
//waymo_open_dataset/math:polygon2d_test                                 PASSED in 0.2s
//waymo_open_dataset/math:vec2d_test                                     PASSED in 0.2s
//waymo_open_dataset/metrics:breakdown_generator_test                    PASSED in 0.2s
//waymo_open_dataset/metrics:detection_metrics_test                      PASSED in 0.2s
//waymo_open_dataset/metrics:hungarian_test                              PASSED in 0.4s
//waymo_open_dataset/metrics:iou_test                                    PASSED in 0.2s
//waymo_open_dataset/metrics:matcher_test                                PASSED in 0.2s
//waymo_open_dataset/metrics:metrics_utils_test                          PASSED in 0.2s
//waymo_open_dataset/metrics:mot_test                                    PASSED in 0.2s
//waymo_open_dataset/metrics:tracking_metrics_test                       PASSED in 0.5s
//third_party/camera/ops:camera_model_ops_test                           FAILED in 17.9s
  /home/zhengkai/.cache/bazel/_bazel_zhengkai/0be34b2c09cc692a11612dfa2e39d953/execroot/__main__/bazel-out/k8-opt/testlogs/third_party/camera/ops/camera_model_ops_test/test.log
//waymo_open_dataset/metrics/ops:detection_metrics_ops_test              FAILED in 18.2s
  /home/zhengkai/.cache/bazel/_bazel_zhengkai/0be34b2c09cc692a11612dfa2e39d953/execroot/__main__/bazel-out/k8-opt/testlogs/waymo_open_dataset/metrics/ops/detection_metrics_ops_test/test.log
//waymo_open_dataset/metrics/python:detection_metrics_test               FAILED in 18.4s
  /home/zhengkai/.cache/bazel/_bazel_zhengkai/0be34b2c09cc692a11612dfa2e39d953/execroot/__main__/bazel-out/k8-opt/testlogs/waymo_open_dataset/metrics/python/detection_metrics_test/test.log
//waymo_open_dataset/utils:box_utils_test                                FAILED in 16.6s
  /home/zhengkai/.cache/bazel/_bazel_zhengkai/0be34b2c09cc692a11612dfa2e39d953/execroot/__main__/bazel-out/k8-opt/testlogs/waymo_open_dataset/utils/box_utils_test/test.log
//waymo_open_dataset/utils:range_image_utils_test                        FAILED in 18.7s
  /home/zhengkai/.cache/bazel/_bazel_zhengkai/0be34b2c09cc692a11612dfa2e39d953/execroot/__main__/bazel-out/k8-opt/testlogs/waymo_open_dataset/utils/range_image_utils_test/test.log
//waymo_open_dataset/utils:transform_utils_test                          FAILED in 15.6s
  /home/zhengkai/.cache/bazel/_bazel_zhengkai/0be34b2c09cc692a11612dfa2e39d953/execroot/__main__/bazel-out/k8-opt/testlogs/waymo_open_dataset/utils/transform_utils_test/test.log

Executed 20 out of 20 tests: 14 tests pass and 6 fail locally.
INFO: Build completed, 6 tests FAILED, 21 total actions
`

Any suggestion?

**Comment by peisun1115** [comment]
can you copy paste one of the error msg? for example, /home/zhengkai/.cache/bazel/_bazel_zhengkai/0be34b2c09cc692a11612dfa2e39d953/execroot/main/bazel-out/k8-opt/testlogs/waymo_open_dataset/utils/transform_utils_test/test.log

**Comment by jiangzhengkai** [comment]
Thanks for your quick reply, this is the error log.

`
Traceback (most recent call last):
  File "/home/zhengkai/.cache/bazel/_bazel_zhengkai/0be34b2c09cc692a11612dfa2e39d953/sandbox/linux-sandbox/1231/execroot/__main__/bazel-out/k8-opt/bin/third_party/camera/ops/camera_model_ops_test.runfiles/__main__/third_party/camera/ops/camera_model_ops_test.py", line 151, in testCameraModel
    with self.test_session(graph=g) as sess:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/zhengkai/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/test_util.py", line 2097, in test_session
    with self.session(graph, config, use_gpu, force_gpu) as sess:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/zhengkai/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/test_util.py", line 2020, in session
    with self._create_session(graph, config, force_gpu) as sess:
  File "/home/zhengkai/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/test_util.py", line 2910, in _create_session
    return ErrorLoggingSession(graph=graph, config=prepare_config(config))
  File "/home/zhengkai/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1585, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/zhengkai/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 699, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InvalidArgumentError: device CUDA:0 not supported by XLA service
        while setting up XLA_GPU_JIT device number 0
`

**Comment by peisun1115** [comment]
Looks like something related to your tf. 

What is your tensorflow version? Are you able to run code like 

python3 waymo_open_dataset/utils/range_image_utils_test.py ?

**Comment by jiangzhengkai** [comment]
My tensorflow verion:
>>> tensorflow.__version__
'2.0.0'

**Comment by peisun1115** [comment]
I do not know what is going on. A quick search on Google shows:

https://github.com/IndicoDataSolutions/finetune/issues/423

I think you compiled successfully. If you need those python code, just use our pre-compiled pip package. If you need those cc tools, i think what you have is good enough. You can try to run those cc tools.

**Comment by jiangzhengkai** [comment]
It seems that there is error when runing python3 waymo_open_dataset/utils/range_image_utils_test.py


Traceback (most recent call last):
  File "waymo_open_dataset/utils/range_image_utils_test.py", line 195, in test_build_range_image_from_point_cloud_from_range_image
    range_image_size=[5, width]))
TypeError: build_range_image_from_point_cloud() got an unexpected keyword argument 'point_features'

Traceback (most recent call last):
  File "waymo_open_dataset/utils/range_image_utils_test.py", line 323, in test_encode_lidar_features
    lidar_features_encoded = range_image_utils.encode_lidar_features(
AttributeError: module 'waymo_open_dataset.utils.range_image_utils' has no attribute 'encode_lidar_features'

**Comment by peisun1115** [comment]
This is because you did not install the package. 

https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md

(search Use pre-compiled pip/pip3 packages)

**Comment by jiangzhengkai** [comment]
Hi, First many thanks for your reply, However, there is still CUDA_OUT_OF_MEMORY Error? I could not find a solution!

Output log

//waymo_open_dataset/metrics:mot_test                                    PASSED in 0.2s
//waymo_open_dataset/metrics:tracking_metrics_test                       PASSED in 0.5s
//waymo_open_dataset/metrics/python:detection_metrics_test               PASSED in 29.1s
//waymo_open_dataset/utils:transform_utils_test                          PASSED in 26.6s
//waymo_open_dataset/metrics/ops:detection_metrics_ops_test              FAILED in 23.6s
  /home/zhengkai/.cache/bazel/_bazel_zhengkai/0be34b2c09cc692a11612dfa2e39d953/execroot/__main__/bazel-out/k8-opt/testlogs/waymo_open_dataset/metrics/ops/detection_metrics_ops_test/test.log
//waymo_open_dataset/utils:box_utils_test                                FAILED in 23.7s
  /home/zhengkai/.cache/bazel/_bazel_zhengkai/0be34b2c09cc692a11612dfa2e39d953/execroot/__main__/bazel-out/k8-opt/testlogs/waymo_open_dataset/utils/box_utils_test/test.log
//waymo_open_dataset/utils:range_image_utils_test                        FAILED in 23.7s
  /home/zhengkai/.cache/bazel/_bazel_zhengkai/0be34b2c09cc692a11612dfa2e39d953/execroot/__main__/bazel-out/k8-opt/testlogs/waymo_open_dataset/utils/range_image_utils_test/test.log

Executed 20 out of 20 tests: 17 tests pass and 3 fail locally.
INFO: Build completed, 3 tests FAILED, 21 total actions


Here is the log information:

_MEMORY: out of memory
2020-04-07 08:44:44.300156: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 15.28M (16024064 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-07 08:44:44.318359: F tensorflow/stream_executor/cuda/cuda_driver.cc:175] Check failed: err == cudaSuccess || err == cudaErrorInvalidValue Unexpected CUDA error: out of memory
Fatal Python error: Aborted

**Comment by jiangzhengkai** [comment]
My machine is 24G, thus I cannot why this happens when compiling ?

**Comment by peisun1115** [comment]
i doubt this is related to our code. Try to check your gpu to see who is using the memory. Maybe try to run another non-waymo GPU code to see whether you can successfully run

**Comment by jiangzhengkai** [comment]
I just give up build.

I try to use metric op in python.

When I run detection_metrics_test.py function, there are still some problems? any suggestion?

`
2020-04-08 01:57:57.511807: I waymo_open_dataset/metrics/ops/detection_metrics_ops.cc:153] Computing detection metrics for 4000 predicted boxes.
Fatal Python error: Segmentation fault

Thread 0x00007f9036b57740 (most recent call first):
  File "/home/zhengkai/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443 in _call_tf_sessionrun
  File "/home/zhengkai/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350 in _run_fn
  File "/home/zhengkai/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365 in _do_call
  File "/home/zhengkai/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359 in _do_run
  File "/home/zhengkai/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180 in _run
  File "/home/zhengkai/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956 in run
  File "/home/zhengkai/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/test_util.py", line 1557 in run
  File "waymo_common.py", line 97 in <dictcomp>
  File "waymo_common.py", line 97 in _EvalValueOps
  File "waymo_common.py", line 120 in testAPBasic
  File "/usr/lib/python3.6/unittest/case.py", line 605 in run
  File "/usr/lib/python3.6/unittest/case.py", line 653 in __call__
  File "/usr/lib/python3.6/unittest/suite.py", line 122 in run
  File "/usr/lib/python3.6/unittest/suite.py", line 84 in __call
`
