### ISSUE TITLE
`range_image_utils` errors with tensorflow 2.2.0, python 3.6.8

### ISSUE THREAD

**Issue by ConnorNovak** [waymo-research/waymo-open-dataset#155]
**Traceback:**
```
Traceback (most recent call last):
  File "waymo2numpy.py", line 22, in <module>
    from waymo_open_dataset.utils import range_image_utils
  File "/home/cnovak/Workspaces/catkin_ws/src/ml_person_detection/env/lib/python3.6/site-packages/waymo_open_dataset/utils/range_image_utils.py", line 59, in <module>
    pool_method=tf.unsorted_segment_max):
AttributeError: module 'tensorflow' has no attribute 'unsorted_segment_max'
```
**Locations**
This error occurred in three separate locations for the `range_image_utils.py` file.
1. line 59: `tf.unsorted_segment_max`
2. line 226: `tf.unsorted_segment_min`
3. line 416: `tf.unsorted_segment_max`

**Solution:**
Nearest I can tell, this error occurred because [TensorFlow V2.2.0](https://www.tensorflow.org/api_docs/python/tf/math/unsorted_segment_max#expandable-1-label) no longer supports the [old alias](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/math/unsorted_segment_max#aliases). Changing all `tf` references to `tf.math` on each of the three lines solves the issue.

Is this a case of me having the wrong versions of tensorflow, python, and or waymo-open-dataset, or an actual bug that should be fixed? Hard to believe someone hasn't hit this yet . . .

**Comment by ConnorNovak** [comment]
Underlying issue was pip installing `waymo-open-dataset==1.0.1`.
Fixed by uninstalling and re-installing `waymo-open-dataset-tf-2-1-0==1.2.0`, as per tutorial.
