### ISSUE TITLE
Parse tfrecord files failed

### ISSUE THREAD

**Issue by boundles** [waymo-research/waymo-open-dataset#457]
Hi, I encounter a error as follow when reading perception dataset with python multiprocessing, pls do me a favor, thanks anyone.

`Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "tools/waymo_parser.py", line 51, in parse_one
    for frame_idx, data in enumerate(dataset):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 761, in __next__
    return self._next_internal()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 744, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2728, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 6941, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: /nfs/s3_common_dataset/waymo_perception_v1.3/validation/segment-1071392229495085036_1844_790_1864_790_with_camera_labels.tfrecord; Invalid argument [Op:IteratorGetNext]
"""`

**Comment by alexgorban** [comment]
Hi, 

It is hard to identify root cause of this error without source code, but it looks like you are using TensorFlow to parse tfrecords.
Did you try to read this segment using the tutorial [notebook](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial.ipynb)?

Note that tf.data API already supports [parallelized processing](https://www.tensorflow.org/guide/data_performance#parallelizing_data_transformation) and multiprocessing can interact badly with TensorFlow, causing nondeterministic deadlocks. For high performance data pipelines using tf.data is recommended (e.g. [tf.data: Parallelize loading step](https://stackoverflow.com/questions/61370108/tf-data-parallelize-loading-step).

**Comment by boundles** [comment]
> Hi,
> 
> It is hard to identify root cause of this error without source code, but it looks like you are using TensorFlow to parse tfrecords. Did you try to read this segment using the tutorial [notebook](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial.ipynb)?
> 
> Note that tf.data API already supports [parallelized processing](https://www.tensorflow.org/guide/data_performance#parallelizing_data_transformation) and multiprocessing can interact badly with TensorFlow, causing nondeterministic deadlocks. For high performance data pipelines using tf.data is recommended (e.g. [tf.data: Parallelize loading step](https://stackoverflow.com/questions/61370108/tf-data-parallelize-loading-step).

ok, thanks a lot, I will try it.

**Comment by alexgorban** [comment]
I'll close this issue for now, please feel free to reopen it if you have more questions.
