### ISSUE TITLE
cannot import name 'keypoint_pb2' from 'waymo_open_dataset.protos'

### ISSUE THREAD

**Issue by erdemuysalx** [waymo-research/waymo-open-dataset#505]
Dear all,

I am trying to setup the repo by following the quick start tutorial and colab notebook, however process is really painfull.

Even though pip installation is successfull, I receive `ImportError: cannot import name 'dataset_pb2' from 'waymo_open_dataset'` error when I am trying to run demo codes; which points that installation process does not create `dataset_pb2` proto files automatically. Therefore I created them manually by using this [answer](https://github.com/waymo-research/waymo-open-dataset/issues/35#issuecomment-536451837) to the relavent issue. 

After resolving the previous error I am getting another similar error `ImportError: cannot import name 'keypoint_pb2' from 'waymo_open_dataset.protos' `.

Error output:
`Traceback (most recent call last):
  File "demo.py", line 9, in <module>
    from waymo_open_dataset.utils import frame_utils
  File "/lhome/rauysal/waymo-od/waymo_open_dataset/utils/frame_utils.py", line 21, in <module>
    from waymo_open_dataset import dataset_pb2
  File "/lhome/rauysal/waymo-od/waymo_open_dataset/dataset_pb2.py", line 16, in <module>
    from waymo_open_dataset import label_pb2 as waymo__open__dataset_dot_label__pb2
  File "/lhome/rauysal/waymo-od/waymo_open_dataset/label_pb2.py", line 16, in <module>
    from waymo_open_dataset.protos import keypoint_pb2 as waymo__open__dataset_dot_protos_dot_keypoint__pb2
ImportError: cannot import name 'keypoint_pb2' from 'waymo_open_dataset.protos' (/lhome/rauysal/waymo-od/waymo_open_dataset/protos/__init__.py)
`

System info:
OS = Ubuntu Bionic 18.04.6 LTS 
Python Version = 3.7.13
Installation method = pre-compiled pip package via `pip3 install waymo-open-dataset-tf-2-6-0 --user`
[TF and Keras compatibility](https://github.com/keras-team/keras#release-and-compatibility) checked, both are version 2.6.0.

**Comment by erdemuysalx** [comment]
protoc ./waymo_open_dataset/protos/keypoint.proto -- python_out=.

**Comment by erdemuysalx** [comment]
`protoc ./waymo_open_dataset/protos/keypoint.proto -- python_out=.`
