### ISSUE TITLE
Problems with Parsing the Motion tf record data

### ISSUE THREAD

**Issue by Sou0602** [waymo-research/waymo-open-dataset#624]
Hello, I was trying to load the motion data with the tf record, following the tutorial, https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_motion.ipynb. But using a single tf example proto, I get the following error : 

`2023-04-08 11:54:14.536235: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE: forward compatibility was attempted on non supported HW
2023-04-08 11:54:14.536262: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: nsh1609-1
2023-04-08 11:54:14.536266: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: nsh1609-1
2023-04-08 11:54:14.536383: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 515.105.1
2023-04-08 11:54:14.536400: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 515.86.1
2023-04-08 11:54:14.536404: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 515.86.1 does not match DSO version 515.105.1 -- cannot find working devices in this configuration
2023-04-08 11:54:14.536603: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-08 11:54:14.550074: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2023-04-08 11:54:14.560810: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Key: roadgraph_samples/xyz.  Can't parse serialized Example.
Traceback (most recent call last):
  File "data_viz_tut.py", line 157, in <module>
    parsed = tf.io.parse_single_example(data, features_description)
  File "/home/nsh1609/anaconda3/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/home/nsh1609/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/parsing_ops.py", line 452, in parse_single_example_v2
    return parse_example_v2(serialized, features, example_names, name)
  File "/home/nsh1609/anaconda3/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/home/nsh1609/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/parsing_ops.py", line 314, in parse_example_v2
    outputs = _parse_example_raw(serialized, example_names, params, name=name)
  File "/home/nsh1609/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/parsing_ops.py", line 350, in _parse_example_raw
    outputs = gen_parsing_ops.parse_example_v2(
  File "/home/nsh1609/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/gen_parsing_ops.py", line 718, in parse_example_v2
    return parse_example_v2_eager_fallback(
  File "/home/nsh1609/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/gen_parsing_ops.py", line 812, in parse_example_v2_eager_fallback
    _result = _execute.execute(b"ParseExampleV2", num_sparse + len(sparse_types)
  File "/home/nsh1609/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: roadgraph_samples/xyz.  Can't parse serialized Example. [Op:ParseExampleV2]
`
From looking around, I found that this happens if the Fixed Length sizes is different or not mentioned in the features descriptor. can someone help me navigate this issue ?

**Comment by Raghuram-Veeramallu** [comment]
Facing the same issue with all the "roadgraph_samples/*" features. Can someone help us resolve this issue?

**Comment by Zachs-Playground** [comment]
Hey guys. I got stuck on this issue too. I just found a solution https://github.com/waymo-research/waymo-open-dataset/issues/343

**So, ignore the following lines that are in the tutorial:**

dataset = tf.data.TFRecordDataset(FILENAME, compression_type='')
data = next(dataset.as_numpy_iterator())
parsed = tf.io.parse_single_example(data, features_description)

**Use this code instead:**
import numpy as np
from waymo_open_dataset.protos import scenario_pb2 
FILENAME = '../data/scenario/uncompressed_scenario_training_20s_training_20s.tfrecord-00000-of-01000'
dataset = tf.data.TFRecordDataset(FILENAME)
scenario_data = []
for data in dataset:
    proto_string = data.numpy()
    proto = scenario_pb2.Scenario()
    proto.ParseFromString(proto_string)
    scenario_data.append(proto)

This code works for the data inside the _./uncompressed_ folder, but it does not work for the ones in the _./tf_example_ folder. I do not know why.

**Comment by scott-ettinger** [comment]
Thanks for flagging this. In the latest version of the dataset, the number of roadgraph samples has increased to 30000.  A temporary workaround is to change the shapes from 20000 to 30000.  We will update the tutorial with the new input shapes shortly.

**Comment by Raghuram-Veeramallu** [comment]
> Thanks for flagging this. In the latest version of the dataset, the number of roadgraph samples has increased to 30000. A temporary workaround is to change the shapes from 20000 to 30000. We will update the tutorial with the new input shapes shortly.

@scott-ettinger Thanks for your clarification. This change resolved the issue for me.

**Comment by xDido** [comment]
Hello, I'm facing the same issue although samples has been updated to 30000.
