### ISSUE TITLE
ERROR about waymo_dataset_v2.0.0

### ISSUE THREAD

**Issue by Cxz-dev** [waymo-research/waymo-open-dataset#646]
I followed the tutorial_v2, but got an error as follows：

2023-04-20 21:03:08.629419: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-20 21:03:08.756921: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/melodic/lib:/usr/local/cuda-10.0/lib64
2023-04-20 21:03:08.756950: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-04-20 21:03:09.837589: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/melodic/lib:/usr/local/cuda-10.0/lib64
2023-04-20 21:03:09.837747: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/melodic/lib:/usr/local/cuda-10.0/lib64
2023-04-20 21:03:09.837759: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "convert_waymo_to_kitti.py", line 10, in <module>
    from waymo_open_dataset import v2
  File "/home/cxz/anaconda3/envs/waymo/lib/python3.8/site-packages/waymo_open_dataset/v2/__init__.py", line 19, in <module>
    from waymo_open_dataset.v2 import column_types as _column_types
  File "/home/cxz/anaconda3/envs/waymo/lib/python3.8/site-packages/waymo_open_dataset/v2/column_types.py", line 25, in <module>
    from waymo_open_dataset.v2 import component
  File "/home/cxz/anaconda3/envs/waymo/lib/python3.8/site-packages/waymo_open_dataset/v2/component.py", line 31, in <module>
    class Component(metaclass=abc.ABCMeta):
  File "/home/cxz/anaconda3/envs/waymo/lib/python3.8/site-packages/waymo_open_dataset/v2/component.py", line 64, in Component
    def from_dict(cls, columns: dict[str, Any]) -> 'Component':
TypeError: 'type' object is not subscriptable

My code is：

#@title Initial setup
from typing import Optional
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import tensorflow as tf
import dask.dataframe as dd
from waymo_open_dataset import v2

dataset_dir = '/home/cxz/waymo_dataset_v2.0.0'

context_name = '10504764403039842352_460_000_480_000'

def read(tag: str) -> dd.DataFrame:
  """Creates a Dask DataFrame for the component specified by its tag."""
  paths = tf.io.gfile.glob(f'{dataset_dir}/{tag}/{context_name}.parquet')
  return dd.read_parquet(paths)

lidar_df = read('lidar')
lidar_pose_df = read('lidar_pose')

Anyone can give me some suggestions？ Thank u！

**Comment by Erin-July** [comment]
I have the same issue. So how to solve it?

**Comment by Erin-July** [comment]
I solved this problem by replacing python 3.8 with python 3.9.
`conda install python=3.9`

**Comment by xcyan** [comment]
Hi @Erin-July 

Thanks for posting! Just let you know that python 3.10 has been tested:
https://github.com/waymo-research/waymo-open-dataset/blob/master/src/waymo_open_dataset/requirements.txt

If you run into another issue, it might be good to follow what's suggested. 

Since you have resolved the problem, can we close the ticket now?
