### ISSUE TITLE
Error in waymo package when ploting clouds with maps

### ISSUE THREAD

**Issue by 073501** [waymo-research/waymo-open-dataset#661]
In waymo motion dataset v1.2:
I first install waymo_open_dataset package in tutorial.ipynb:
![image](https://user-images.githubusercontent.com/92313395/236831232-13f9aa78-ee7c-45a9-9ab8-bbc050f0b190.png)
I try to plot point clouds with maps and follow the instruction in tutorial_maps.ipynb:
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    from waymo_open_dataset.utils import plot_maps
  File "/opt/conda/envs/waymo/lib/python3.8/site-packages/waymo_open_dataset/utils/plot_maps.py", line 52, in <module>
    class MapPoints:
  File "/opt/conda/envs/waymo/lib/python3.8/site-packages/waymo_open_dataset/utils/plot_maps.py", line 55, in MapPoints
    x: list[float] = dataclasses.field(default_factory=list)
TypeError: 'type' object is not subscriptable
```
The error message is from waymo package. Is there any bugs in waymo-open-dataset-tf-2-11-0==1.5.1?

**Comment by scott-ettinger** [comment]
Which version of python are you using?  This looks like an error that could happen if your python version is less than 3.0.

**Comment by scott-ettinger** [comment]
Hi.  Thanks for bringing this up, are you running this in colab?

**Comment by jzuern** [comment]
I had the same error. You need to use a Python version >3.8
