### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by YuehaoHuang** [waymo-research/waymo-open-dataset#769]
>>> from waymo_open_dataset import v2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/python/envs/waymo/lib/python3.8/site-packages/waymo_open_dataset/v2/__init__.py", line 19, in <module>
    from waymo_open_dataset.v2 import column_types as _column_types
  File "/path/python/envs/waymo/lib/python3.8/site-packages/waymo_open_dataset/v2/column_types.py", line 27, in <module>
    from waymo_open_dataset.v2 import component
  File "/path/python/envs/waymo/lib/python3.8/site-packages/waymo_open_dataset/v2/component.py", line 32, in <module>
    class Component(metaclass=abc.ABCMeta):
  File "/path/python/envs/waymo/lib/python3.8/site-packages/waymo_open_dataset/v2/component.py", line 65, in Component
    def from_dict(cls: Type[_T], columns: dict[str, Any]) -> _T:
TypeError: 'type' object is not subscriptable

**Comment by ChocolateDave** [comment]
I have encountered a similar issue. Please make sure your Python version is higher than Python 3.9 since the type annotation `dict[str, Any]` is only valid for those versions. (See [here](https://stackoverflow.com/questions/75202610/typeerror-type-object-is-not-subscriptable-python) for your reference)
