### ISSUE TITLE
Can not decode images

### ISSUE THREAD

**Issue by huohuo-1** [waymo-research/waymo-open-dataset#9]
Hello, 

I can't show images following the tutorial. What should I do?

Thanks!

This is the log

Traceback (most recent call last):
  File "/home/user/.env/dl3/lib/python3.7/site-packages/tensorflow/python/ops/gen_image_ops.py", line 1169, in decode_jpeg
    "acceptable_fraction", acceptable_fraction, "dct_method", dct_method)
tensorflow.python.eager.core._FallbackException: This function does not handle the case of the path where all inputs are not already EagerTensors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Waymo.py", line 77, in <module>
    [3, 3, index+1])
  File "Waymo.py", line 34, in image_show
    plt.imshow(tf.image.decode_jpeg(data), cmap=cmap)
  File "/home/user/.env/dl3/lib/python3.7/site-packages/tensorflow/python/ops/gen_image_ops.py", line 1178, in decode_jpeg
    name=name, ctx=_ctx)
  File "/home/user/.env/dl3/lib/python3.7/site-packages/tensorflow/python/ops/gen_image_ops.py", line 1255, in decode_jpeg_eager_fallback
    contents = _ops.convert_to_tensor(contents, _dtypes.string)
  File "/home/user/.env/dl3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1087, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/home/user/.env/dl3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1145, in convert_to_tensor_v2
    as_ref=False)
  File "/home/user/.env/dl3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1224, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/user/.env/dl3/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 305, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/user/.env/dl3/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 246, in constant
    allow_broadcast=True)
  File "/home/user/.env/dl3/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 254, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/user/.env/dl3/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 115, in convert_to_eager_tensor
    return ops.EagerTensor(value, handle, device, dtype)
TypeError: Cannot convert provided value to EagerTensor. Provided value: bytearray(b'

**Comment by peisun1115** [comment]
How did you run the tutorial? Did you see this error when running it in https://colab.sandbox.google.com? or locally?

**Comment by peisun1115** [comment]
Also what is your tensorflow version?

**Comment by huohuo-1** [comment]
> Also what is your tensorflow version?

My tensorflow version is 1.14.0

**Comment by huohuo-1** [comment]
> How did you run the tutorial? Did you see this error when running it in https://colab.sandbox.google.com? or locally?

I ran the tutorial in jupyter notebook and see this error.

**Comment by peisun1115** [comment]
The current tutorial is supposed to run https://colab.sandbox.google.com directly by following

https://colab.sandbox.google.com/github/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial.ipynb

We can provide a tutorial that can run locally sometime soon.

**Comment by peisun1115** [comment]
We have released 1.0.1

You can follow steps in https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_local.ipynb 
to run the tutorial locally

**Comment by peisun1115** [comment]
I am closing this. Feel free to reopen if you still have questions.
